### ISSUE TITLE
обработка eval

### ISSUE THREAD

**Issue by QiV** [RubaXa/Error.stack#2]
вот такой стек:
```
TypeError: Cannot read property 'appendChild' of null
    at build_banner12987844 (eval at <anonymous> (http://otvet.mail.ru/build/lmd.js?1425299727697:1:25417), <anonymous>:39:24) 
    at http://ad.mail.ru/dynamic?shop=61
```

пытается взять сорс так:
http://rubaxa.github.io/Error.stack/eval%20at%20%3Canonymous%3E%20(http://otvet.mail.ru/build/lmd.js?1425299727697

ua: Mozilla/5.0 (Windows NT 6.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36 OPR/27.0.1689.76

**Comment by QiV** [comment]
```
URIError: URI malformed
  at decodeURIComponent (native)
  at http://otvet.mail.ru/build/lmd.js?1425473741404:5:26699
  at Function.sa (http://otvet.mail.ru/build/lmd.js?1425473741404:4:22408)
  at r.extend._extractParameters (http://otvet.mail.ru/build/lmd.js?1425473741404:5:26672)
  at Object.callback (http://otvet.mail.ru/build/lmd.js?1425473741404:5:26076)
  at http://otvet.mail.ru/build/lmd.js?1425473741404:5:29237
  at Function.ma (http://otvet.mail.ru/build/lmd.js?1425473741404:4:23907)
  at r.extend.loadUrl (http://otvet.mail.ru/build/lmd.js?1425473741404:5:29181)
  at r.extend.start (http://otvet.mail.ru/build/lmd.js?1425473741404:5:28692)
  at a.exports.m.Router.extend.initialize (http://otvet.mail.ru/build/lmd.js?1425473741404:1:9011)
```

**Comment by RubaXa** [comment]
@QiV А мне казалос что-то ещё было, не?
И главное как это интерпретировать? :hankey:

**Comment by QiV** [comment]
Было, но после уставки проксей починилось))) 
хз как это интерпритируется((
может разбивать at fn (eval at <anonymous> (source:l:c), <anonymous>:l:c) регекспом?

**Comment by RubaXa** [comment]
Да я уже разобрался.

**Comment by RubaXa** [comment]
готово. Но советую тебе больше не сжимать файлы в одну строчку, нужно бить на чанки по 200-500 символов.

**Comment by QiV** [comment]
не, ну так можно и разным файликам прийти) попробую поковырять углифай, наверняка искаропке умеет.

**Comment by RubaXa** [comment]
Причем тут это? Все нормальные люди так делаю, просто большинству плевать на дебаг, вот они и не задумываются, а остальные ограничивают длинную чанка.

**Comment by QiV** [comment]
А вот такой вот стек реально запилить? это Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0 (расставил переносы строк после col). Ошибается в подсветке в каждом из пунктов стека...

Backbone/</c@http://otvet.mail.ru/build/lmd.js?1429534452478:5:13413
.Backbone/</t.Events.trigger@http://otvet.mail.ru/build/lmd.js?1429534452478:5:12920
.Backbone/</<.set@http://otvet.mail.ru/build/lmd.js?1429534452478:5:15364
[\"page-question-model\"]/a.exports<.fetch/<@http://otvet.mail.ru/build/lmd.js?1429534452478:10:19513
e/<@http://otvet.mail.ru/build/lmd.js?1429534452478:5:31508
g@http://otvet.mail.ru/build/lmd.js?1429534452478:7:7249
b@http://otvet.mail.ru/build/lmd.js?1429534452478:7:7419
.services/Ht.api/
r@http://otvet.mail.ru/build/lmd.js?1429534452478:7:31641
.$/</it.Callbacks/
d@http://otvet.mail.ru/build/lmd.js?1429534452478:2:16341
.$/</it.Callbacks/u.fireWit
h@http://otvet.mail.ru/build/lmd.js?1429534452478:2:17163
a@http://otvet.mail.ru/build/lmd.js?1429534452478:3:30944
.$/</</<.send/
t@http://otvet.mail.ru/build/lmd.js?1429534452478:4:4788

**Comment by QiV** [comment]
наверно так будет правильнее:

Backbone/</c@http://otvet.mail.ru/build/lmd.js?1429534452478:5:13413
.Backbone/</t.Events.trigger@http://otvet.mail.ru/build/lmd.js?1429534452478:5:12920
.Backbone/</<.set@http://otvet.mail.ru/build/lmd.js?1429534452478:5:15364
[\"page-question-model\"]/a.exports<.fetch/<@http://otvet.mail.ru/build/lmd.js?1429534452478:10:19513
e/<@http://otvet.mail.ru/build/lmd.js?1429534452478:5:31508
g@http://otvet.mail.ru/build/lmd.js?1429534452478:7:7249
b@http://otvet.mail.ru/build/lmd.js?1429534452478:7:7419
.services/Ht.api/r@http://otvet.mail.ru/build/lmd.js?1429534452478:7:31641
.$/</it.Callbacks/d@http://otvet.mail.ru/build/lmd.js?1429534452478:2:16341
.$/</it.Callbacks/u.fireWith@http://otvet.mail.ru/build/lmd.js?1429534452478:2:17163
a@http://otvet.mail.ru/build/lmd.js?1429534452478:3:30944
.$/</</<.send/t@http://otvet.mail.ru/build/lmd.js?1429534452478:4:4788

**Comment by QiV** [comment]
падает вот тут ```var before = bugLine.substr(0, pos) + '/*!B*/';```
может игнорить неинформативные участки стека? тупо выводить строку в титульнике?
Error: Failed to execute 'measure' on 'Performance': The mark 'start-page-question-init-view823' does not exist.
at Error (native)
at Object.t (http://otvet.mail.ru/build/lmd.js?1430311801298:10:23983)
at Object.n.(anonymous function) [as done] (http://otvet.mail.ru/build/lmd.js?1430311801298:6:14667)
at Object.n.then (http://otvet.mail.ru/build/lmd.js?1430311801298:6:14930)
at http://otvet.mail.ru/build/lmd.js?1430311801298:10:24303
